-- 已存在数据库的一次性菜单权限初始化脚本；新数据库无需单独执行。
CREATE TABLE IF NOT EXISTS pintrip_admin_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_key VARCHAR(64) NOT NULL UNIQUE,
    parent_key VARCHAR(64),
    menu_name VARCHAR(64) NOT NULL,
    menu_hint VARCHAR(128) NOT NULL,
    route VARCHAR(128),
    icon VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_admin_menu_status CHECK (status IN (1, 2))
);

CREATE TABLE IF NOT EXISTS pintrip_admin_role_menu (
    role_id BIGINT NOT NULL REFERENCES pintrip_admin_role (id) ON DELETE CASCADE,
    menu_id BIGINT NOT NULL REFERENCES pintrip_admin_menu (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, menu_id)
);

INSERT INTO pintrip_admin_menu (menu_key, parent_key, menu_name, menu_hint, route, icon, sort_order)
VALUES
    ('system', NULL, '系统管理', '账号、权限与审计', NULL, 'settings', 10),
    ('menus', 'system', '菜单管理', '菜单与权限设置', '#/menus', 'settings', 11),
    ('users', 'system', '用户管理', '账号与状态', '#/users', 'users', 12),
    ('roles', 'system', '角色管理', '角色与授权', '#/roles', 'roles', 13),
    ('logs', 'system', '日志记录', '操作日志、登录日志', '#/logs', 'logs', 14),
    ('agent', NULL, 'Agent 管理', '内容、任务与模型', NULL, 'tasks', 20),
    ('dashboard', 'agent', '运营看板', '全局概览', '#/dashboard', 'dashboard', 21),
    ('knowledge', 'agent', '知识库', '攻略与向量', '#/knowledge', 'knowledge', 22),
    ('imports', 'agent', '导入日志', '素材处理', '#/imports', 'imports', 23),
    ('tasks', 'agent', 'Agent 任务', '运行与重试', '#/tasks', 'tasks', 24),
    ('prompts', 'agent', 'Prompt 模板', '版本管理', '#/prompts', 'prompts', 25)
ON CONFLICT (menu_key) DO UPDATE SET
    parent_key = EXCLUDED.parent_key, menu_name = EXCLUDED.menu_name,
    menu_hint = EXCLUDED.menu_hint, route = EXCLUDED.route,
    icon = EXCLUDED.icon, sort_order = EXCLUDED.sort_order;

INSERT INTO pintrip_admin_role_menu (role_id, menu_id)
SELECT role.id, menu.id FROM pintrip_admin_role role CROSS JOIN pintrip_admin_menu menu
WHERE role.role_code = 'SUPER_ADMIN' ON CONFLICT DO NOTHING;

INSERT INTO pintrip_admin_role_menu (role_id, menu_id)
SELECT role.id, menu.id FROM pintrip_admin_role role JOIN pintrip_admin_menu menu
ON menu.menu_key IN ('agent', 'dashboard', 'knowledge', 'imports', 'tasks', 'prompts')
WHERE role.role_code = 'OPERATOR' ON CONFLICT DO NOTHING;
