CREATE TABLE IF NOT EXISTS pintrip_admin_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    email VARCHAR(128),
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(64) NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    failed_login_count INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    password_changed_at TIMESTAMPTZ NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_admin_user_username UNIQUE (username),
    CONSTRAINT uk_admin_user_email UNIQUE (email),
    CONSTRAINT ck_admin_user_status CHECK (status IN (1, 2, 3))
);

CREATE INDEX IF NOT EXISTS idx_admin_user_status
    ON pintrip_admin_user (status);

COMMENT ON TABLE pintrip_admin_user IS '运营后台账号';
COMMENT ON COLUMN pintrip_admin_user.status IS '1正常，2禁用，3锁定';

CREATE TABLE IF NOT EXISTS pintrip_admin_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(64) NOT NULL,
    role_name VARCHAR(64) NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_admin_role_code UNIQUE (role_code),
    CONSTRAINT ck_admin_role_status CHECK (status IN (1, 2))
);

COMMENT ON TABLE pintrip_admin_role IS '运营角色';

CREATE TABLE IF NOT EXISTS pintrip_admin_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_pintrip_admin_user_role_user
        FOREIGN KEY (user_id) REFERENCES pintrip_admin_user (id),
    CONSTRAINT fk_pintrip_admin_user_role_role
        FOREIGN KEY (role_id) REFERENCES pintrip_admin_role (id)
);

CREATE INDEX IF NOT EXISTS idx_admin_user_role_role_id
    ON pintrip_admin_user_role (role_id);

COMMENT ON TABLE pintrip_admin_user_role IS '运营账号角色关系';

INSERT INTO pintrip_admin_role (role_code, role_name)
VALUES
    ('SUPER_ADMIN', '超级管理员'),
    ('OPERATOR', '普通运营人员')
ON CONFLICT (role_code) DO NOTHING;
