CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS pintrip_admin_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    email VARCHAR(128),
    password_hash VARCHAR(100) NOT NULL,
    display_name VARCHAR(64) NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    failed_login_count INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    password_changed_at TIMESTAMPTZ NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_admin_user_username UNIQUE (username),
    CONSTRAINT uk_admin_user_email UNIQUE (email),
    CONSTRAINT ck_admin_user_status CHECK (status IN (1, 2, 3))
);

CREATE INDEX IF NOT EXISTS idx_admin_user_status
    ON pintrip_admin_user (status);

COMMENT ON TABLE pintrip_admin_user IS '运营后台账号';
COMMENT ON COLUMN pintrip_admin_user.status IS '1正常，2禁用，3锁定';

CREATE TABLE IF NOT EXISTS pintrip_admin_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(64) NOT NULL,
    role_name VARCHAR(64) NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_admin_role_code UNIQUE (role_code),
    CONSTRAINT ck_admin_role_status CHECK (status IN (1, 2))
);

COMMENT ON TABLE pintrip_admin_role IS '运营角色';

CREATE TABLE IF NOT EXISTS pintrip_admin_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_pintrip_admin_user_role_user
        FOREIGN KEY (user_id) REFERENCES pintrip_admin_user (id),
    CONSTRAINT fk_pintrip_admin_user_role_role
        FOREIGN KEY (role_id) REFERENCES pintrip_admin_role (id)
);

CREATE INDEX IF NOT EXISTS idx_admin_user_role_role_id
    ON pintrip_admin_user_role (role_id);

COMMENT ON TABLE pintrip_admin_user_role IS '运营账号角色关系';

INSERT INTO pintrip_admin_role (role_code, role_name)
VALUES
    ('SUPER_ADMIN', '超级管理员'),
    ('OPERATOR', '普通运营人员')
ON CONFLICT (role_code) DO NOTHING;

CREATE TABLE IF NOT EXISTS pintrip_admin_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_key VARCHAR(64) NOT NULL,
    parent_key VARCHAR(64),
    menu_name VARCHAR(64) NOT NULL,
    menu_hint VARCHAR(128) NOT NULL,
    route VARCHAR(128),
    icon VARCHAR(32) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_admin_menu_key UNIQUE (menu_key),
    CONSTRAINT ck_admin_menu_status CHECK (status IN (1, 2))
);

CREATE TABLE IF NOT EXISTS pintrip_admin_role_menu (
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, menu_id),
    CONSTRAINT fk_admin_role_menu_role FOREIGN KEY (role_id)
        REFERENCES pintrip_admin_role (id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_role_menu_menu FOREIGN KEY (menu_id)
        REFERENCES pintrip_admin_menu (id) ON DELETE CASCADE
);

INSERT INTO pintrip_admin_menu (
    menu_key, parent_key, menu_name, menu_hint, route, icon, sort_order
) VALUES
    ('system', NULL, '系统管理', '账号、权限与审计', NULL, 'settings', 10),
    ('menus', 'system', '菜单管理', '菜单与权限设置', '#/menus', 'settings', 11),
    ('users', 'system', '用户管理', '账号与状态', '#/users', 'users', 12),
    ('roles', 'system', '角色管理', '角色与授权', '#/roles', 'roles', 13),
    ('logs', 'system', '日志记录', '操作日志、登录日志', '#/logs', 'logs', 14),
    ('agent', NULL, 'Agent 管理', '内容、任务与模型', NULL, 'tasks', 20),
    ('dashboard', 'agent', '运营看板', '全局概览', '#/dashboard', 'dashboard', 21),
    ('knowledge', 'agent', '知识库', '攻略与向量', '#/knowledge', 'knowledge', 22),
    ('imports', 'agent', '导入日志', '素材处理', '#/imports', 'imports', 23),
    ('tasks', 'agent', 'Agent 任务', '运行与重试', '#/tasks', 'tasks', 24),
    ('prompts', 'agent', 'Prompt 模板', '版本管理', '#/prompts', 'prompts', 25)
ON CONFLICT (menu_key) DO UPDATE SET
    parent_key = EXCLUDED.parent_key,
    menu_name = EXCLUDED.menu_name,
    menu_hint = EXCLUDED.menu_hint,
    route = EXCLUDED.route,
    icon = EXCLUDED.icon,
    sort_order = EXCLUDED.sort_order;

INSERT INTO pintrip_admin_role_menu (role_id, menu_id)
SELECT role.id, menu.id
FROM pintrip_admin_role role
CROSS JOIN pintrip_admin_menu menu
WHERE role.role_code = 'SUPER_ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO pintrip_admin_role_menu (role_id, menu_id)
SELECT role.id, menu.id
FROM pintrip_admin_role role
JOIN pintrip_admin_menu menu
  ON menu.menu_key IN ('agent', 'dashboard', 'knowledge', 'imports', 'tasks', 'prompts')
WHERE role.role_code = 'OPERATOR'
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS pintrip_knowledge_document (
    id VARCHAR(32) PRIMARY KEY,
    title VARCHAR(80) NOT NULL,
    destination VARCHAR(40) NOT NULL,
    source VARCHAR(40) NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    chunk_count INTEGER NOT NULL CHECK (chunk_count > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'indexing',
    error_message VARCHAR(1000),
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_knowledge_source_type CHECK (source_type IN ('operator', 'user')),
    CONSTRAINT ck_knowledge_status CHECK (status IN ('indexing', 'published', 'failed', 'offline'))
);

CREATE INDEX IF NOT EXISTS idx_knowledge_document_destination
    ON pintrip_knowledge_document (destination);
CREATE INDEX IF NOT EXISTS idx_knowledge_document_status
    ON pintrip_knowledge_document (status);

CREATE TABLE IF NOT EXISTS pintrip_knowledge_chunk (
    id UUID PRIMARY KEY,
    knowledge_id VARCHAR(32) NOT NULL,
    chunk_index INTEGER NOT NULL CHECK (chunk_index >= 0),
    content TEXT NOT NULL,
    embedding vector(512),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_chunk_position UNIQUE (knowledge_id, chunk_index),
    CONSTRAINT fk_knowledge_chunk_document
        FOREIGN KEY (knowledge_id) REFERENCES pintrip_knowledge_document (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_knowledge_chunk_document
    ON pintrip_knowledge_chunk (knowledge_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_chunk_embedding
    ON pintrip_knowledge_chunk
    USING hnsw (embedding vector_cosine_ops);

COMMENT ON TABLE pintrip_knowledge_document IS '运营导入和用户沉淀的攻略知识';
COMMENT ON TABLE pintrip_knowledge_chunk IS '攻略知识切块及其语义向量';
